[build]
    command = "hugo --buildDrafts --contentDir=./content"
    publish = "public"

[context.production.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
    command = "HUGO_BASEURL=http://localhost hugo --buildDrafts --contentDir=./content"

[build.environment]
    HUGO_VERSION = "v0.126.1"
