# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
# "404.html" = "selected"
# "robots.txt" = "selected"
# "partials/svg.html" = "selected"
# "partials/cover.html" = "selected"
# "partials/index_profile.html" = "selected"
# "partials/head.html" = "selected"
# "partials/post_canonical.html" = "selected"
# "partials/post_meta.html" = "selected"
# "partials/anchored_headings.html" = "selected"
# "partials/social_icons.html" = "selected"
# "partials/translation_list.html" = "selected"
# "partials/author.html" = "selected"
# "partials/comments.html" = "selected"
# "partials/extend_footer.html" = "selected"
# "partials/extend_head.html" = "selected"
# "partials/home_info.html" = "selected"
# "partials/post_nav_links.html" = "selected"
# "partials/footer.html" = "selected"
# "partials/header.html" = "selected"
# "partials/toc.html" = "selected"
# "partials/breadcrumbs.html" = "selected"
# "partials/share_icons.html" = "selected"
# "partials/edit_post.html" = "selected"
# "partials/templates/twitter_cards.html" = "selected"
# "partials/templates/schema_json.html" = "selected"
# "partials/templates/opengraph.html" = "selected"
# "partials/templates/_funcs/get-page-images.html" = "selected"
# "shortcodes/inTextImg.html" = "selected"
# "shortcodes/ltr.html" = "selected"
# "shortcodes/rawhtml.html" = "selected"
# "shortcodes/rtl.html" = "selected"
# "shortcodes/figure.html" = "selected"
# "shortcodes/collapse.html" = "selected"
# "_default/archives.html" = "selected"
# "_default/list.html" = "selected"
# "_default/rss.xml" = "selected"
# "_default/single.html" = "selected"
# "_default/terms.html" = "selected"
# "_default/search.html" = "selected"
# "_default/baseof.html" = "selected"
# "_default/index.json" = "selected"
# "_default/_markup/render-image.html" = "selected"
