# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
 "series.md" = "selected"
# "series.eu.md" = "selected"
# "search.es.md" = "selected"
# "archive.fr.md" = "selected"
# "search.fr.md" = "selected"
# "search.ca.md" = "selected"
# "categories.ca.md" = "selected"
# "search.md" = "selected"
# "search.eu.md" = "selected"
# "tags.es.md" = "selected"
 "tags.md" = "selected"
# "series.fr.md" = "selected"
# "categories.es.md" = "selected"
# "archive.es.md" = "selected"
 "categories.md" = "selected"
# "series.ca.md" = "selected"
 "archive.md" = "selected"
# "tags.eu.md" = "selected"
# "categories.eu.md" = "selected"
# "archive.eu.md" = "selected"
# "series.es.md" = "selected"
# "categories.fr.md" = "selected"
# "tags.ca.md" = "selected"
# "archive.ca.md" = "selected"
# "tags.fr.md" = "selected"
# "posts/La-Cuponera.md" = "selected"
# "posts/CodeArena.eu.md" = "selected"
# "posts/how-to-make-money-trashback.ca.md" = "selected"
# "posts/CodeArena.ca.md" = "selected"
# "posts/Walking-Money.md" = "selected"
# "posts/Bat-Brave-Rewards.eu.md" = "selected"
# "posts/how-to-make-money-google-rewards.es.md" = "selected"
# "posts/get-crow-workers.ca.md" = "selected"
# "posts/Trashback-Rewards.md" = "selected"
# "posts/how-to-make-money-trashback.es.md" = "selected"
# "posts/how-to-make-money-google-rewards.eu.md" = "selected"
# "posts/how-to-make-money-solving-git-issues.es.md" = "selected"
# "posts/Internet-From-Shared-Scooter.md" = "selected"
# "posts/how-to-make-money-trashback.fr.md" = "selected"
# "posts/how-to-make-money-trashback.eu.md" = "selected"
# "posts/Bat-Brave-Rewards.fr.md" = "selected"
# "posts/get-paid-for-housekeeping.md" = "selected"
# "posts/learn-and-earn-crypto.eu.md" = "selected"
# "posts/get-paid-for-housekeeping.eu.md" = "selected"
# "posts/CodeArena.fr.md" = "selected"
# "posts/too-good-to-go.es.md" = "selected"
# "posts/Trashback-Rewards.eu.md" = "selected"
# "posts/too-good-to-go.fr.md" = "selected"
# "posts/Google-Opinion-Rewards.eu.md" = "selected"
# "posts/how-to-make-money-google-rewards.ca.md" = "selected"
# "posts/La-Cuponera.eu.md" = "selected"
# "posts/Walking-Money.fr.md" = "selected"
# "posts/too-good-to-go.md" = "selected"
# "posts/La-Cuponera.fr.md" = "selected"
# "posts/CodeArena.md" = "selected"
# "posts/learn-and-earn-crypto.md" = "selected"
# "posts/too-good-to-go.ca.md" = "selected"
# "posts/Google-Opinion-Rewards.fr.md" = "selected"
# "posts/stacking-crypto.md" = "selected"
# "posts/stacking-crypto.ca.md" = "selected"
# "posts/Google-Opinion-Rewards.md" = "selected"
# "posts/learn-and-earn-crypto.ca.md" = "selected"
# "posts/Bat-Brave-Rewards.es.md" = "selected"
# "posts/Trashback-Rewards.es.md" = "selected"
# "posts/Internet-From-Shared-Scooter.ca.md" = "selected"
# "posts/Sweatcoin-Walking-Rewards.fr.md" = "selected"
# "posts/how-to-make-money-google-rewards.fr.md" = "selected"
# "posts/learn-and-earn-crypto.es.md" = "selected"
# "posts/get-paid-for-housekeeping.fr.md" = "selected"
# "posts/how-to-make-money-solving-git-issues.md" = "selected"
# "posts/Sweatcoin-Walking-Rewards.es.md" = "selected"
# "posts/Bat-Brave-Rewards.ca.md" = "selected"
# "posts/Internet-From-Shared-Scooter.fr.md" = "selected"
# "posts/Internet-From-Shared-Scooter.eu.md" = "selected"
# "posts/Walking-Money.eu.md" = "selected"
# "posts/get-crow-workers.eu.md" = "selected"
# "posts/Trashback-Rewards.ca.md" = "selected"
# "posts/how-to-make-money-solving-git-issues.eu.md" = "selected"
# "posts/Walking-Money.es.md" = "selected"
# "posts/how-to-make-money-solving-git-issues.ca.md" = "selected"
# "posts/get-crow-workers.md" = "selected"
# "posts/Sweatcoin-Walking-Rewards.eu.md" = "selected"
# "posts/Google-Opinion-Rewards.es.md" = "selected"
# "posts/learn-and-earn-crypto.fr.md" = "selected"
# "posts/get-crow-workers.fr.md" = "selected"
# "posts/how-to-make-money-trashback.md" = "selected"
# "posts/Sweatcoin-Walking-Rewards.ca.md" = "selected"
# "posts/get-paid-for-housekeeping.ca.md" = "selected"
# "posts/Internet-From-Shared-Scooter.es.md" = "selected"
# "posts/stacking-crypto.fr.md" = "selected"
# "posts/Sweatcoin-Walking-Rewards.md" = "selected"
# "posts/stacking-crypto.es.md" = "selected"
# "posts/La-Cuponera.ca.md" = "selected"
# "posts/stacking-crypto.eu.md" = "selected"
# "posts/Google-Opinion-Rewards.ca.md" = "selected"
# "posts/La-Cuponera.es.md" = "selected"
# "posts/how-to-make-money-google-rewards.md" = "selected"
# "posts/Trashback-Rewards.fr.md" = "selected"
# "posts/too-good-to-go.eu.md" = "selected"
# "posts/CodeArena.es.md" = "selected"
# "posts/get-paid-for-housekeeping.es.md" = "selected"
# "posts/how-to-make-money-solving-git-issues.fr.md" = "selected"
# "posts/Walking-Money.ca.md" = "selected"
# "posts/get-crow-workers.es.md" = "selected"
# "posts/Bat-Brave-Rewards.md" = "selected"
# 
